#!/usr/bin/env sh
set -eu
ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
python3 "$ROOT/tools/init_database.py"
python3 "$ROOT/tools/export_browser_data.py"
python3 "$ROOT/tests/validate_catalogue.py"
python3 "$ROOT/tests/validate_command_verification.py"
python3 "$ROOT/tests/test_command_verification.py"
python3 "$ROOT/tests/validate_command_documentation.py"
python3 "$ROOT/tests/test_command_documentation.py"
python3 "$ROOT/tests/test_version_profiles.py"
python3 "$ROOT/tests/test_generated_data.py"
python3 "$ROOT/tests/validate_generated_data.py"
if command -v node >/dev/null 2>&1; then
  node --check "$ROOT/js/app.js"
  node --check "$ROOT/assets/vendor/ipaddr.js"
  node --check "$ROOT/js/config-builder.js"
  node --check "$ROOT/js/builder-ui.js"
  node --check "$ROOT/data/catalogue-data.js"
  node --check "$ROOT/data/command-verification.js"
  node --check "$ROOT/data/command-documentation.js"
  node "$ROOT/tests/validate_runtime.js"
  node "$ROOT/tests/validate_config_builder.js"
  node "$ROOT/tests/validate_builder_ui.js"
fi
printf '\nRebuild complete. Open %s/index.html\n' "$ROOT"
